### ISSUE TITLE
Test Plan Issues nº1 Part 1/2

### ISSUE THREAD

**Issue by Gregory-Pagnoux** [algosup/2024-2025-project-1-fpga-team-1#3]
What's written:

line 40 - on **a** hardware
line 40 - Frogger's original gameplay**,** while adding
line 42 - its various copies**,** to those
line 44 - (3 errors) Before **create** the game and **test** it, we need understand
line 48 - a busy road, then an equally busy river
line 48 - the river and reach
line 63/64/65 - the original **frogger**
line 71 - work correctly**,** and whether
line 74 - (3 errors) Add a **win** page **which** appears when all levels are **finish**.
line 75 - Add a menu **which** allows to 
line 77 - Frog's **apparence**

What needs to be written:

line 40 - on hardware
line 40 - Frogger's original gameplay while adding
line 42 - its various copies to those
line 44 - (3 errors) Before **creating** the game and **testing** it, we need **to** understand
line 48 - a busy road, **and** then an equally busy river
line 48 - the river**,** and reach
line 63/64/65 - the original **Frogger**
line 71 - work correctly and whether
line 74 - (3 errors) Add a **winning** page **that** appears when all levels are **finished**.
line 75 - Add a menu **that** allows to
line 77 - Frog's **appearance**

**Comment by Mamoru-fr** [comment]
it is done

**Comment by Gregory-Pagnoux** [comment]
You forgot 3 errors

What's written:

line 72 - (2 errors) Add a win page **which** appears when all levels are **finish**.
line 75 - Frog's **appearence**

What needs to be written:

line 72 - (2 errors) Add a winning page **that** appears when all levels are **finished**.
line 75 - Frog's **appearance**

**Comment by Mamoru-fr** [comment]
I did'nt see it, its done
