### ISSUE TITLE
Technical_specification Issues nº1

### ISSUE THREAD

**Issue by Mamoru-fr** [algosup/2024-2025-project-1-fpga-team-1#5]
What's written: 

line 72 - [FPGA Board name]
line 127 - D. Constraints**
line 132 - E. Risks and Assumptions**
line 139 - A. Graphic Convention**
line 146 - reg [15:0] frog_sprite [0:255]; // Store 16x16 sprite data

What needs to be written:

line 72 - FPGA Go-board
line 127 - D. Constraints
line 132 - E. Risks and Assumptions
line 139 - A. Graphic Convention
line 146 - reg [31:0] frog_sprite [0:255]; // Store 32x32 sprite data

**Comment by mathislebel** [comment]
it is done
