### ISSUE TITLE
Project Charter Issues N°1

### ISSUE THREAD

**Issue by Mamoru-fr** [algosup/2024-2025-project-1-fpga-team-1#6]
Error in the order on 2. Project Scope - line 26 to 31.

it is write : 
1. recreate the basic game (map, character, obstacles)
2. add bonuses
3. add score
4. add menu
5. multiples level and difficulties
6. add differents themes

But it need write : 
1. Recreate the basic game (map, character, obstacles)
2. Add menu
3. Add score
4. Add Bonuses
5. Multiples level and difficulties
6. Add differents themes

**Comment by Gregory-Pagnoux** [comment]
it's done @Mamoru-fr

**Comment by Gregory-Pagnoux** [comment]
new modification done @Mamoru-fr
